server:
  port: 12345
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://rm-2vc8716230t2bxcuwdo.mysql.cn-chengdu.rds.aliyuncs.com/ymforyou?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: foryou
    password: Wohui8013
mybatis-plus:
  global-config:
    banner: false
  type-aliases-package: com.hui.foryou.entity
logging:
  level:
    root: info

xxl:
  job:
    enable: false
    admin:
      address: http://http://121.196.212.89:9999
    accessToken:
    executor:
      appname: ${spring.application.name}
      address:
      ip:
      port: 9999
      logpath: logs
      logretentiondays: 30